# Generated by Django 3.2.1 on 2023-02-22 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_create_book', 'Can create book')]},
        ),
    ]
