# Generated by Django 3.2.17 on 2023-02-19 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_asdsad'),
    ]

    operations = [
        migrations.DeleteModel(
            name='asdsad',
        ),
    ]
