# Generated by Django 3.2.1 on 2023-03-28 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='answer_time',
            new_name='answerTime',
        ),
    ]
