# Generated by Django 3.2.1 on 2023-03-28 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_rename_answer_time_question_answertime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='countdown_time',
            new_name='countdownTime',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='public_id',
            new_name='publicId',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='question_no',
            new_name='questionNo',
        ),
    ]
